version: '3'
services:
  postgres:
    image: postgres:10
    volumes:
      - dev-postgres-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: react_redux_rails_list_app
volumes:
  dev-postgres-volume:
